# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  pull_request:
    branches: [development]
    paths-ignore:
        - 'DOCUMENTATION/**'
        - 'OMOP_VOCABULARIES/**'
        - 'StatusReport/**'
  workflow_dispatch:

name: build_and_test

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.2.2'

      - name: Set RENV_PATHS_ROOT
        shell: bash
        run: echo "RENV_PATHS_ROOT=${{ runner.temp }}/renv" >> $GITHUB_ENV

      - name: Restore Renv package cache
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: compiled-libraries-R-${{ hashFiles('SCRIPTS/R_repo_management/renv.lock') }}
          restore-keys: compiled-libraries-R-

      - name: Install renv dependencies
        working-directory: SCRIPTS/R_repo_management
        shell: Rscript {0}
        run: renv::restore()      

      - name: Copy input_omop_vocabulary.zip from latest release        
        uses: robinraju/release-downloader@v1.7
        with:
          latest: true
          fileName: "input_omop_vocabulary.zip"
          out-file-path: "OMOP_VOCABULARIES"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: unzip input_omop_vocabulary.zip
        working-directory: OMOP_VOCABULARIES
        shell: bash
        run: |
         rm input_omop_vocabulary/*
         unzip input_omop_vocabulary.zip

      - name: Run R script
        working-directory: SCRIPTS/R_repo_management
        shell: Rscript {0}
        run: source("R_scripts/update_repository.R")

      - name: test
        shell: bash
        run: ls OMOP_VOCABULARIES/input_omop_vocabulary

      - name: Upload dashboard to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dashboard-artifact
          path: StatusReport/dashboard.html 